version: "3"

services:
  nginx:
    image: my-nginx-service
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - app

  app:
    image: coals0329/blog-front:latest
    ports:
      - "3000:3000"
    expose:
      - 3000
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge